name: ğŸšš Continuous Delivery
on:
  workflow_run:
    workflows:
      - ğŸ” Continuous Integration
    types:
      - completed
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¦ Checkout
        uses: actions/checkout@v3
      - name: ğŸš€ Deploy to remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd /home/${{ secrets.USERNAME }}/${{ secrets.REPO }}
            if test -d "k8s-ci-cd"
                cd k8s-ci-cd
                git pull origin main
            else
                git clone git@github.com:PunGrumpy/k8s-ci-cd.git
            end
            cd deployment
            docker compose up -d
