name: ğŸ” Continuous Integration
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
env:
  APP_NAME: argocd-app
jobs:
  build:
    name: ğŸ”¨ Build
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¦ Checkout
        uses: actions/checkout@v3
      - name: ğŸ—ï¸ Setup
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: ğŸ‘·â€â™‚ï¸ Build and Push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.APP_NAME }}:latest, ${{ secrets.DOCKER_USERNAME }}/${{ env.APP_NAME }}:${{ github.sha }}
          context: ./web-server
  deploy:
    name: ğŸš€ Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¦ Checkout
        uses: actions/checkout@v3
      - name: ğŸ—ï¸ Setup Kustomize
        uses: imranismail/setup-kustomize@v2
        with:
          kustomize-version: '5.1.1'
      - name: ğŸ­ Update Kubernetes Resource
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          cd k8s
          kustomize edit set image ${{ env.APP_NAME }}=${{ secrets.DOCKER_USERNAME }}/${{ env.APP_NAME }}:${{ github.sha }}
          cat kustomization.yml
      - name: ğŸš¢ Commit files
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "action@github.com"
          git commit -am "chore: update image to tag `${{ github.sha }}`"
      - name: ğŸš€ Push files
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
